version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install tox
  pre_build:
    commands:
      - echo Running test...
      - tox
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 866824485776.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=866824485776.dkr.ecr.us-east-1.amazonaws.com/mlops-cicd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - ls -l
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing container image definitions file...
      - printf '[{"name":"mlops-cicd","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
reports:
  pytest_reports:
    files:
      - Prediction_test_report.xml
      - API_test_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
artifacts:
    files: imagedefinitions.json